// Generated by gencpp from file nao_interaction_msgs/GetAudioMasterVolume.msg
// DO NOT EDIT!


#ifndef NAO_INTERACTION_MSGS_MESSAGE_GETAUDIOMASTERVOLUME_H
#define NAO_INTERACTION_MSGS_MESSAGE_GETAUDIOMASTERVOLUME_H

#include <ros/service_traits.h>


#include <nao_interaction_msgs/GetAudioMasterVolumeRequest.h>
#include <nao_interaction_msgs/GetAudioMasterVolumeResponse.h>


namespace nao_interaction_msgs
{

struct GetAudioMasterVolume
{

typedef GetAudioMasterVolumeRequest Request;
typedef GetAudioMasterVolumeResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetAudioMasterVolume
} // namespace nao_interaction_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::nao_interaction_msgs::GetAudioMasterVolume > {
  static const char* value()
  {
    return "6a2d45c5fcf9fd89299667da81b32d64";
  }

  static const char* value(const ::nao_interaction_msgs::GetAudioMasterVolume&) { return value(); }
};

template<>
struct DataType< ::nao_interaction_msgs::GetAudioMasterVolume > {
  static const char* value()
  {
    return "nao_interaction_msgs/GetAudioMasterVolume";
  }

  static const char* value(const ::nao_interaction_msgs::GetAudioMasterVolume&) { return value(); }
};


// service_traits::MD5Sum< ::nao_interaction_msgs::GetAudioMasterVolumeRequest> should match 
// service_traits::MD5Sum< ::nao_interaction_msgs::GetAudioMasterVolume > 
template<>
struct MD5Sum< ::nao_interaction_msgs::GetAudioMasterVolumeRequest>
{
  static const char* value()
  {
    return MD5Sum< ::nao_interaction_msgs::GetAudioMasterVolume >::value();
  }
  static const char* value(const ::nao_interaction_msgs::GetAudioMasterVolumeRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::nao_interaction_msgs::GetAudioMasterVolumeRequest> should match 
// service_traits::DataType< ::nao_interaction_msgs::GetAudioMasterVolume > 
template<>
struct DataType< ::nao_interaction_msgs::GetAudioMasterVolumeRequest>
{
  static const char* value()
  {
    return DataType< ::nao_interaction_msgs::GetAudioMasterVolume >::value();
  }
  static const char* value(const ::nao_interaction_msgs::GetAudioMasterVolumeRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::nao_interaction_msgs::GetAudioMasterVolumeResponse> should match 
// service_traits::MD5Sum< ::nao_interaction_msgs::GetAudioMasterVolume > 
template<>
struct MD5Sum< ::nao_interaction_msgs::GetAudioMasterVolumeResponse>
{
  static const char* value()
  {
    return MD5Sum< ::nao_interaction_msgs::GetAudioMasterVolume >::value();
  }
  static const char* value(const ::nao_interaction_msgs::GetAudioMasterVolumeResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::nao_interaction_msgs::GetAudioMasterVolumeResponse> should match 
// service_traits::DataType< ::nao_interaction_msgs::GetAudioMasterVolume > 
template<>
struct DataType< ::nao_interaction_msgs::GetAudioMasterVolumeResponse>
{
  static const char* value()
  {
    return DataType< ::nao_interaction_msgs::GetAudioMasterVolume >::value();
  }
  static const char* value(const ::nao_interaction_msgs::GetAudioMasterVolumeResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // NAO_INTERACTION_MSGS_MESSAGE_GETAUDIOMASTERVOLUME_H
