// Generated by gencpp from file nao_interaction_msgs/LearnFaceRequest.msg
// DO NOT EDIT!


#ifndef NAO_INTERACTION_MSGS_MESSAGE_LEARNFACEREQUEST_H
#define NAO_INTERACTION_MSGS_MESSAGE_LEARNFACEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/String.h>

namespace nao_interaction_msgs
{
template <class ContainerAllocator>
struct LearnFaceRequest_
{
  typedef LearnFaceRequest_<ContainerAllocator> Type;

  LearnFaceRequest_()
    : name()  {
    }
  LearnFaceRequest_(const ContainerAllocator& _alloc)
    : name(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::String_<ContainerAllocator>  _name_type;
  _name_type name;





  typedef boost::shared_ptr< ::nao_interaction_msgs::LearnFaceRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::nao_interaction_msgs::LearnFaceRequest_<ContainerAllocator> const> ConstPtr;

}; // struct LearnFaceRequest_

typedef ::nao_interaction_msgs::LearnFaceRequest_<std::allocator<void> > LearnFaceRequest;

typedef boost::shared_ptr< ::nao_interaction_msgs::LearnFaceRequest > LearnFaceRequestPtr;
typedef boost::shared_ptr< ::nao_interaction_msgs::LearnFaceRequest const> LearnFaceRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::nao_interaction_msgs::LearnFaceRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::nao_interaction_msgs::LearnFaceRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace nao_interaction_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'nav_msgs': ['/opt/ros/kinetic/share/nav_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'trajectory_msgs': ['/opt/ros/kinetic/share/trajectory_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'nao_interaction_msgs': ['/home/looly/catkin_new/src/nao_interaction/nao_interaction_msgs/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::nao_interaction_msgs::LearnFaceRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::nao_interaction_msgs::LearnFaceRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::nao_interaction_msgs::LearnFaceRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::nao_interaction_msgs::LearnFaceRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nao_interaction_msgs::LearnFaceRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nao_interaction_msgs::LearnFaceRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::nao_interaction_msgs::LearnFaceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0fce35bd9f5b27a63eb9b0e831759a0b";
  }

  static const char* value(const ::nao_interaction_msgs::LearnFaceRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0fce35bd9f5b27a6ULL;
  static const uint64_t static_value2 = 0x3eb9b0e831759a0bULL;
};

template<class ContainerAllocator>
struct DataType< ::nao_interaction_msgs::LearnFaceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "nao_interaction_msgs/LearnFaceRequest";
  }

  static const char* value(const ::nao_interaction_msgs::LearnFaceRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::nao_interaction_msgs::LearnFaceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/String name\n\
\n\
================================================================================\n\
MSG: std_msgs/String\n\
string data\n\
";
  }

  static const char* value(const ::nao_interaction_msgs::LearnFaceRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::nao_interaction_msgs::LearnFaceRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.name);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LearnFaceRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::nao_interaction_msgs::LearnFaceRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::nao_interaction_msgs::LearnFaceRequest_<ContainerAllocator>& v)
  {
    s << indent << "name: ";
    s << std::endl;
    Printer< ::std_msgs::String_<ContainerAllocator> >::stream(s, indent + "  ", v.name);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NAO_INTERACTION_MSGS_MESSAGE_LEARNFACEREQUEST_H
