// Generated by gencpp from file nao_interaction_msgs/LearnFaceResponse.msg
// DO NOT EDIT!


#ifndef NAO_INTERACTION_MSGS_MESSAGE_LEARNFACERESPONSE_H
#define NAO_INTERACTION_MSGS_MESSAGE_LEARNFACERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Bool.h>

namespace nao_interaction_msgs
{
template <class ContainerAllocator>
struct LearnFaceResponse_
{
  typedef LearnFaceResponse_<ContainerAllocator> Type;

  LearnFaceResponse_()
    : result()  {
    }
  LearnFaceResponse_(const ContainerAllocator& _alloc)
    : result(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Bool_<ContainerAllocator>  _result_type;
  _result_type result;





  typedef boost::shared_ptr< ::nao_interaction_msgs::LearnFaceResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::nao_interaction_msgs::LearnFaceResponse_<ContainerAllocator> const> ConstPtr;

}; // struct LearnFaceResponse_

typedef ::nao_interaction_msgs::LearnFaceResponse_<std::allocator<void> > LearnFaceResponse;

typedef boost::shared_ptr< ::nao_interaction_msgs::LearnFaceResponse > LearnFaceResponsePtr;
typedef boost::shared_ptr< ::nao_interaction_msgs::LearnFaceResponse const> LearnFaceResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::nao_interaction_msgs::LearnFaceResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::nao_interaction_msgs::LearnFaceResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace nao_interaction_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'nav_msgs': ['/opt/ros/kinetic/share/nav_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'trajectory_msgs': ['/opt/ros/kinetic/share/trajectory_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'nao_interaction_msgs': ['/home/looly/catkin_new/src/nao_interaction/nao_interaction_msgs/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::nao_interaction_msgs::LearnFaceResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::nao_interaction_msgs::LearnFaceResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::nao_interaction_msgs::LearnFaceResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::nao_interaction_msgs::LearnFaceResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nao_interaction_msgs::LearnFaceResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nao_interaction_msgs::LearnFaceResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::nao_interaction_msgs::LearnFaceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c2420602a83d8ccc0f3664e0daafab6c";
  }

  static const char* value(const ::nao_interaction_msgs::LearnFaceResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc2420602a83d8cccULL;
  static const uint64_t static_value2 = 0x0f3664e0daafab6cULL;
};

template<class ContainerAllocator>
struct DataType< ::nao_interaction_msgs::LearnFaceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "nao_interaction_msgs/LearnFaceResponse";
  }

  static const char* value(const ::nao_interaction_msgs::LearnFaceResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::nao_interaction_msgs::LearnFaceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Bool result\n\
\n\
\n\
================================================================================\n\
MSG: std_msgs/Bool\n\
bool data\n\
";
  }

  static const char* value(const ::nao_interaction_msgs::LearnFaceResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::nao_interaction_msgs::LearnFaceResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.result);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LearnFaceResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::nao_interaction_msgs::LearnFaceResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::nao_interaction_msgs::LearnFaceResponse_<ContainerAllocator>& v)
  {
    s << indent << "result: ";
    s << std::endl;
    Printer< ::std_msgs::Bool_<ContainerAllocator> >::stream(s, indent + "  ", v.result);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NAO_INTERACTION_MSGS_MESSAGE_LEARNFACERESPONSE_H
