// Generated by gencpp from file nao_interaction_msgs/LearnFace.msg
// DO NOT EDIT!


#ifndef NAO_INTERACTION_MSGS_MESSAGE_LEARNFACE_H
#define NAO_INTERACTION_MSGS_MESSAGE_LEARNFACE_H

#include <ros/service_traits.h>


#include <nao_interaction_msgs/LearnFaceRequest.h>
#include <nao_interaction_msgs/LearnFaceResponse.h>


namespace nao_interaction_msgs
{

struct LearnFace
{

typedef LearnFaceRequest Request;
typedef LearnFaceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct LearnFace
} // namespace nao_interaction_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::nao_interaction_msgs::LearnFace > {
  static const char* value()
  {
    return "cff8f1ff74895b778f6f5c0b02297a61";
  }

  static const char* value(const ::nao_interaction_msgs::LearnFace&) { return value(); }
};

template<>
struct DataType< ::nao_interaction_msgs::LearnFace > {
  static const char* value()
  {
    return "nao_interaction_msgs/LearnFace";
  }

  static const char* value(const ::nao_interaction_msgs::LearnFace&) { return value(); }
};


// service_traits::MD5Sum< ::nao_interaction_msgs::LearnFaceRequest> should match 
// service_traits::MD5Sum< ::nao_interaction_msgs::LearnFace > 
template<>
struct MD5Sum< ::nao_interaction_msgs::LearnFaceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::nao_interaction_msgs::LearnFace >::value();
  }
  static const char* value(const ::nao_interaction_msgs::LearnFaceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::nao_interaction_msgs::LearnFaceRequest> should match 
// service_traits::DataType< ::nao_interaction_msgs::LearnFace > 
template<>
struct DataType< ::nao_interaction_msgs::LearnFaceRequest>
{
  static const char* value()
  {
    return DataType< ::nao_interaction_msgs::LearnFace >::value();
  }
  static const char* value(const ::nao_interaction_msgs::LearnFaceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::nao_interaction_msgs::LearnFaceResponse> should match 
// service_traits::MD5Sum< ::nao_interaction_msgs::LearnFace > 
template<>
struct MD5Sum< ::nao_interaction_msgs::LearnFaceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::nao_interaction_msgs::LearnFace >::value();
  }
  static const char* value(const ::nao_interaction_msgs::LearnFaceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::nao_interaction_msgs::LearnFaceResponse> should match 
// service_traits::DataType< ::nao_interaction_msgs::LearnFace > 
template<>
struct DataType< ::nao_interaction_msgs::LearnFaceResponse>
{
  static const char* value()
  {
    return DataType< ::nao_interaction_msgs::LearnFace >::value();
  }
  static const char* value(const ::nao_interaction_msgs::LearnFaceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // NAO_INTERACTION_MSGS_MESSAGE_LEARNFACE_H
