// Generated by gencpp from file nao_interaction_msgs/SetAudioMasterVolume.msg
// DO NOT EDIT!


#ifndef NAO_INTERACTION_MSGS_MESSAGE_SETAUDIOMASTERVOLUME_H
#define NAO_INTERACTION_MSGS_MESSAGE_SETAUDIOMASTERVOLUME_H

#include <ros/service_traits.h>


#include <nao_interaction_msgs/SetAudioMasterVolumeRequest.h>
#include <nao_interaction_msgs/SetAudioMasterVolumeResponse.h>


namespace nao_interaction_msgs
{

struct SetAudioMasterVolume
{

typedef SetAudioMasterVolumeRequest Request;
typedef SetAudioMasterVolumeResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetAudioMasterVolume
} // namespace nao_interaction_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::nao_interaction_msgs::SetAudioMasterVolume > {
  static const char* value()
  {
    return "6a2d45c5fcf9fd89299667da81b32d64";
  }

  static const char* value(const ::nao_interaction_msgs::SetAudioMasterVolume&) { return value(); }
};

template<>
struct DataType< ::nao_interaction_msgs::SetAudioMasterVolume > {
  static const char* value()
  {
    return "nao_interaction_msgs/SetAudioMasterVolume";
  }

  static const char* value(const ::nao_interaction_msgs::SetAudioMasterVolume&) { return value(); }
};


// service_traits::MD5Sum< ::nao_interaction_msgs::SetAudioMasterVolumeRequest> should match 
// service_traits::MD5Sum< ::nao_interaction_msgs::SetAudioMasterVolume > 
template<>
struct MD5Sum< ::nao_interaction_msgs::SetAudioMasterVolumeRequest>
{
  static const char* value()
  {
    return MD5Sum< ::nao_interaction_msgs::SetAudioMasterVolume >::value();
  }
  static const char* value(const ::nao_interaction_msgs::SetAudioMasterVolumeRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::nao_interaction_msgs::SetAudioMasterVolumeRequest> should match 
// service_traits::DataType< ::nao_interaction_msgs::SetAudioMasterVolume > 
template<>
struct DataType< ::nao_interaction_msgs::SetAudioMasterVolumeRequest>
{
  static const char* value()
  {
    return DataType< ::nao_interaction_msgs::SetAudioMasterVolume >::value();
  }
  static const char* value(const ::nao_interaction_msgs::SetAudioMasterVolumeRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::nao_interaction_msgs::SetAudioMasterVolumeResponse> should match 
// service_traits::MD5Sum< ::nao_interaction_msgs::SetAudioMasterVolume > 
template<>
struct MD5Sum< ::nao_interaction_msgs::SetAudioMasterVolumeResponse>
{
  static const char* value()
  {
    return MD5Sum< ::nao_interaction_msgs::SetAudioMasterVolume >::value();
  }
  static const char* value(const ::nao_interaction_msgs::SetAudioMasterVolumeResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::nao_interaction_msgs::SetAudioMasterVolumeResponse> should match 
// service_traits::DataType< ::nao_interaction_msgs::SetAudioMasterVolume > 
template<>
struct DataType< ::nao_interaction_msgs::SetAudioMasterVolumeResponse>
{
  static const char* value()
  {
    return DataType< ::nao_interaction_msgs::SetAudioMasterVolume >::value();
  }
  static const char* value(const ::nao_interaction_msgs::SetAudioMasterVolumeResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // NAO_INTERACTION_MSGS_MESSAGE_SETAUDIOMASTERVOLUME_H
