(cl:defpackage nao_interaction_msgs-msg
  (:use )
  (:export
   "<AUDIOSOURCELOCALIZATION>"
   "AUDIOSOURCELOCALIZATION"
   "<FACEDETECTED>"
   "FACEDETECTED"
   "<LANDMARKDETECTED>"
   "LANDMARKDETECTED"
   "<MOVEMENTDETECTED>"
   "MOVEMENTDETECTED"
  ))

